### ISSUE TITLE
引言篇 token 翻译

### ISSUE THREAD

**Issue by Maxwell-Jia** [datawhalechina/so-large-lm#10]
NLP 中将 token 直译成“令牌”似乎并不合适，没有表达出原意，容易引起初学者的疑惑。
不得不承认，中文没有一个合适的词来翻译这个词（语言模型场景下）。为了能够达意，可以翻译成“词元”（抛砖引玉，可能有更合适的词）。
或者像 transformer 这个词一样，直接使用，不翻译。

**Comment by andongBlue** [comment]
谢谢你的提议，我们这边构建了一个专业词表，目前token按照你的建议和结合讨论，我们准备使用词符来表达。
