### ISSUE TITLE
ch10：10.1概述第一段最后一句的表达可能有误

### ISSUE THREAD

**Issue by time1527** [datawhalechina/so-large-lm#22]
![tmp](https://github.com/datawhalechina/so-large-lm/assets/154412155/a95a9f34-a919-437d-8f07-0ce67f48335b)

结合上下文和原lecture “This means that we need to think of the harms as not a property of the text, but in terms of the broader social context”，这句话的意思表达有误（即表达反了）

**Comment by mlw67** [comment]
感谢您对于相关问题的指出，先已将其修正为：这意味着我们需要从更广泛的社会背景来考虑其危害性，而不是从文本的本身属性角度。（这说明着信息的危害是对于人生效的，对于不同人可能同样的信息是不同的效果，而这不是文本的本身属性）
