### ISSUE TITLE
ch01独热编码举例部分修改建议

### ISSUE THREAD

**Issue by Yangyang8462** [datawhalechina/so-large-lm#33]
ch01中，在用独热编码举例那一块：
1. 写<begin>和<end>时用了单引号，预览的时候就显示不出来<begin>和<end>，不知道是不是vscode的问题，我猜想应该是识别成了html的标签，建议使用反引号，这样可以正常显示。
2. 输入序列'ab.b'的编码写的是：[[0,0,0,0],[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,1,0,0],[0,0,0,1]]，'.'的编码应该是[0,0,1,0]，这里有错误。

**Comment by Yangyang8462** [comment]
噢如果是想看成token那种，建议写成 `'<begin>'`，外面包一层反引号。

**Comment by andongBlue** [comment]
我们已经修改了这个问题。
![image](https://github.com/user-attachments/assets/1b748e99-61af-4ce1-8588-b7ac07e9d716)
