### ISSUE TITLE
引言篇可以补充一下生成任务和模拟退火的推导

### ISSUE THREAD

**Issue by Mieluoxxx** [datawhalechina/so-large-lm#4]
**语言模型也可以做生成任务**。语言模型是一种概率模型，它可以根据给定的上下文来预测下一个词的概率分布。我们可以使用语言模型来生成一个序列，其中每个元素都是根据前面元素的条件概率分布来生成的。最纯粹的方法是从语言模型$p$中以概率$p(x_{1:L})$进行采样。表示为：

$x_{1:L} \sim p$

例如，如果我们的语言模型p表示"$x_{1:L}$"的条件概率分布为：

$\begin{aligned}
&P(x_1) = 0.2 \\
&P(x_2 | x_1) = 0.3 \\ 
&P(x_3 | x_1, x_2) = 0.1 \\ 
&P(x_4 | x_1, x_2, x_3) = 0.05 \\ 
&P(x_5 | x_1, x_2, x_3, x_4) = 0.01
\end{aligned}$

那么我们可以按照以下方式生成新的序列："$x_1:x_2:x_3:x_4:x_5$"：

- 首先，我们从语言模型$p$中采样得到"$x_1$"的概率分布：

  - $P(x_1) = 0.2$

- 然后，我们根据"$x_1$"的概率分布和语言模型$p$的条件概率分布来采样得到"$x_2$"的概率分布：

  - $P(x_2 | x_1) = 0.3$

  - $P(x1,x2​)=P(x2​∣x1​)×P(x1​)=0.3×0.2=0.06$

- 接下来，我们根据"$x_1$"和"$x_2$"的概率分布以及语言模型$p$的条件概率分布来采样得到"$x_3$"的概率分布：

  - $P(x_3 | x_1, x_2) = 0.1$

  - $P(x1,x2,x3) = P(x_3 | x_1, x_2) \times P(x1,x2​) = 0.3 \times 0.2  \times 0.1$

- 继续这个过程，我们可以得到"$x_4$"和"$x_5$"的概率分布：

  - $P(x_4 | x_1, x_2, x_3) = 0.05$

  - $P(x1,x2,x3,x4) = P(x4 \mid x1,x2,x3) \times P(x1,x2,x3) = 0.2 \times 0.3 \times 0.1 \times 0.05$

- 最后，我们可以根据"$x_4$"和"$x_5$"的概率分布来生成新的序列："$x_1:x_2:x_3:x_4:x_5$"：

  - "$x_1:x_2:x_3:x_4:x_5$"的概率分布为：$\begin{aligned}
P(x_1:x_2:x_3:x_4:x_5) &=P(x_1) \times P(x_2 | x_1) \times P(x_3 | x_1, x_2) \times P(x_4 | x_1, x_2, x_3) \\& \times P(x_5 | x_1, x_2, x_3, x_4) \\ 
&=0.2 \times 0.3 \times 0.1 \times 0.05 \times 0.01 
\end{aligned}$

然而，如果我们仅将概率提高到  $1/T$  的次方，概率分布可能不会加和到 1。我们可以通过重新标准化分布来解决这个问题。我们将标准化版本  $p_{T}(x_{i}∣x_{1:i−1})∝p(x_{i}∣x_{1:i−1})^{1/T}$ 称为退火条件概率分布。例如：

$\begin{array}{cl}
p(\text { cheese })=0.4, & p(\text { mouse })=0.6 \\
p_{T=0.5}(\text { cheese })=0.31, & \left.p_{T=0.5} \text { (mouse }\right)=0.69 \\
\left.p_{T=0.2} \text { (cheese }\right)=0.12, & p_{T=0.2} \text { (mouse) }=0.88 \\
\left.p_{T=0} \text { (cheese }\right)=0, & \left.p_{T=0} \text { (mouse }\right)=1
\end{array}$

这是一个模拟退火算法中的"**Metropolis准则**"的计算过程。Metropolis准则是一种随机搜索方法，用于在概率空间中寻找函数的**全局最小值**。在这个问题中，我们要找的是使得某个目标函数$p(x)$最小的$x$值，其中$x$是一个离散的样本空间。

给定的概率分布是：

$p(cheese)=0.4, p(mouse)=0.6$

我们想要知道在温度$T=0.5$时，$p_T=0.5​(cheese)$和$p_T=0.5​(mouse)$的值。根据**Metropolis准则**，我们需要计算以下概率：

$p_T=_{0.5}​(cheese∣x_{1:i−1}​)∝p(xi​∣x_{1:i−1}​)^{1/T}$

这里，$x_{1:i−1}$​表示在当前迭代之前的样本集合，$x_i$​表示当前的样本。

这个公式的意思是，在新的温度下，假设我们接受一个新的样本$x_i$，那么这个新样本对应的概率将乘以原概率的($1/T$)次方。

所以，我们可以计算出：

$\begin{aligned}
p_T&=_{0.5}​(cheese∣x_{1:i−1}​)∝p(x_i​∣x_{1:i−1}​)^{1/T} \\&=p(cheese)^{1/T}×p(x_i​∣cheese) 
\\&=0.4^{1/0.5}×0.4
\\&=0.31
\end{aligned}$

同理，我们也可以计算出：

$\begin{aligned}
p_T&=_{0.5}​(mouse∣x_{1:i−1}​)∝p(x_i​∣x_{1:i−1}​)^{1/T}
\\&=p(mouse)^{1/0.5}×p(xi​∣mouse)
\\&=0.6^{1/0.5}×0.6
\\&=0.69
\end{aligned}$

具体来说，这个温度参数会应用于每一步的条件概率分布 $p(x_{i}∣x_{1:i−1})$ ，将其幂变为  $1/T$ 。

**Comment by andongBlue** [comment]
@Mieluoxxx 感谢您的详细过程。这块的数学问题我们会进一步解释的情况，我稍后阅读完您的整体的推导并验证正确后，在下一版本中采纳这个建议。
