### ISSUE TITLE
第一章：引言 翻译错误

### ISSUE THREAD

**Issue by Tangent-90C** [datawhalechina/so-large-lm#5]
这块凭空冒出来了非自回归生成任务的表述，在CS324中并不存在这样的表述，应该是翻译错了

![c520145ee48be90a0bcff7659ef8ef0](https://github.com/datawhalechina/so-large-lm/assets/28804414/ea4a587e-dc87-41a4-888f-dd69ddd07255)

**Comment by andongBlue** [comment]
@Tangent-90C  感谢您的纠错，md 版已经更新，修正了这个笔误 👍。pdf版本会之后统一更新。
