### ISSUE TITLE
第七章，请问为什么似然值是 4/9

### ISSUE THREAD

**Issue by goatduoduo** [datawhalechina/so-large-lm#6]
原文

它被用来训练T5和Gopher模型。给定一个序列$x_{1:L}$，一个分词器$T$是$p\left(x_{1: L}\right)=\prod_{(i, j) \in T} p\left(x_{i: j}\right)$的一个集合。这边给出一个实例：

- 训练数据（字符串）：$𝖺𝖻𝖺𝖻𝖼$
- 分词结果 $T={(1,2),(3,4),(5,5)}$ （其中$V=\{𝖺𝖻,𝖼\}$）
- 似然值：$p(x_{1:L})=2/3⋅2/3⋅1/3=4/9$

在这个例子中，训练数据是字符串"$𝖺𝖻𝖺𝖻𝖼$"。分词结果 $T={(1,2),(3,4),(5,5)}$ 表示将字符串拆分成三个子序列：$(𝖺,𝖻)，(𝖺,𝖻)，(𝖼)$。词汇表$ V=\{𝖺𝖻,𝖼\} $表示了训练数据中出现的所有词汇。

似然值 $p(x_{1:L}) $是根据 unigram 模型计算得出的概率，表示训练数据的似然度。在这个例子中，概率的计算为 $2/3⋅2/3⋅1/3=4/9$。这个值代表了根据 unigram 模型，将训练数据分词为所给的分词结果 $T $的概率。

请问一下 2/3⋅2/3⋅1/3 如果三个分数相乘，那么结果应该是 4/27，那么4/9到底是怎么来的，你最好解释一下。

**Comment by andongBlue** [comment]
谢谢提问，这里你的计算是对的，结果为4/27。

PS: “你最好解释一下。”，下次可以换一个提问的方式。
